def _meta_export_impl(ctx):
    out_meta = ctx.actions.declare_file("meta.yaml")
    ctx.actions.run(
        outputs = [out_meta],
        inputs = [ctx.file.src],
        executable = ctx.executable._aseprite2meta,
        arguments = [
            "--input=" + ctx.file.src.path,
            "--output=" + out_meta.path,
        ],
    )

    return DefaultInfo(files = depset([out_meta]))

meta_export = rule(
    implementation = _meta_export_impl,
    attrs = {
        "_aseprite2meta": attr.label(
            default = "//src/opendata:aseprite2meta",
            executable = True,
            cfg = "exec",
        ),
        "src": attr.label(
            allow_single_file = True,
            doc = "path to JSON metadata file generated by Aseprite export",
        ),
    },
)
